-- Auto-generated by build_manifest.py
-- Normalising VIEW that UNION ALLs all youth_* tables.
-- Re-run build_manifest.py to regenerate after adding new tables.

CREATE OR REPLACE VIEW public.youth_fact AS
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_birth_mother_age_ntpc' AS source_table
  FROM public.youth_birth_mother_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_birth_parent_age_ntpc' AS source_table
  FROM public.youth_birth_parent_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_bureau_activity_ntpc' AS source_table
  FROM public.youth_bureau_activity_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_bureau_program_stats_ntpc' AS source_table
  FROM public.youth_bureau_program_stats_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_commute_census_ntpc' AS source_table
  FROM public.youth_commute_census_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_crime_suspect_age_ntpc' AS source_table
  FROM public.youth_crime_suspect_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_crime_victim_age_ntpc' AS source_table
  FROM public.youth_crime_victim_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_death_age_group_ntpc' AS source_table
  FROM public.youth_death_age_group_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_death_rate_single_age_ntpc' AS source_table
  FROM public.youth_death_rate_single_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_digital_access_age_tw' AS source_table
  FROM public.youth_digital_access_age_tw
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_divorce_age_structure_ntpc' AS source_table
  FROM public.youth_divorce_age_structure_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_divorce_rate_age_ntpc' AS source_table
  FROM public.youth_divorce_rate_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_edu_dropout_ntpc' AS source_table
  FROM public.youth_edu_dropout_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_edu_graduates' AS source_table
  FROM public.youth_edu_graduates
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_edu_registration_ntpc' AS source_table
  FROM public.youth_edu_registration_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_edu_students' AS source_table
  FROM public.youth_edu_students
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_edu_suspend_ntpc' AS source_table
  FROM public.youth_edu_suspend_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_education_age_ntpc' AS source_table
  FROM public.youth_education_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_employee_salary_age_tw' AS source_table
  FROM public.youth_employee_salary_age_tw
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_employment_structure_age_tw' AS source_table
  FROM public.youth_employment_structure_age_tw
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_fertility_rate_age_ntpc' AS source_table
  FROM public.youth_fertility_rate_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_fraud_victim_age_ntpc' AS source_table
  FROM public.youth_fraud_victim_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_housing_burden_ntpc' AS source_table
  FROM public.youth_housing_burden_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_housing_price_index_ntpc' AS source_table
  FROM public.youth_housing_price_index_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_indigenous_education_age_ntpc' AS source_table
  FROM public.youth_indigenous_education_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_labor_participation_age_tw' AS source_table
  FROM public.youth_labor_participation_age_tw
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_marital_status_age_ntpc' AS source_table
  FROM public.youth_marital_status_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_mental_health_antidepressant_tw' AS source_table
  FROM public.youth_mental_health_antidepressant_tw
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_minimum_wage_tw' AS source_table
  FROM public.youth_minimum_wage_tw
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_oas_age_structure_ntpc' AS source_table
  FROM public.youth_oas_age_structure_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_oas_household_dynamics_ntpc' AS source_table
  FROM public.youth_oas_household_dynamics_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_oas_population_age_ntpc' AS source_table
  FROM public.youth_oas_population_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_occupational_injury_age_ntpc' AS source_table
  FROM public.youth_occupational_injury_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_pop_single_age' AS source_table
  FROM public.youth_pop_single_age
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_rental_market_ntpc' AS source_table
  FROM public.youth_rental_market_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_salary_initial_by_education' AS source_table
  FROM public.youth_salary_initial_by_education
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_salary_initial_history_pdf' AS source_table
  FROM public.youth_salary_initial_history_pdf
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_sexual_assault_perpetrator_age_ntpc' AS source_table
  FROM public.youth_sexual_assault_perpetrator_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_sexual_assault_victim_age_ntpc' AS source_table
  FROM public.youth_sexual_assault_victim_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_skill_certification_age_tw' AS source_table
  FROM public.youth_skill_certification_age_tw
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_suicide_death_age_ntpc' AS source_table
  FROM public.youth_suicide_death_age_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_suicide_report_old_ntpc' AS source_table
  FROM public.youth_suicide_report_old_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_traffic_fatal_ntpc' AS source_table
  FROM public.youth_traffic_fatal_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_traffic_injury_ntpc' AS source_table
  FROM public.youth_traffic_injury_ntpc
UNION ALL
SELECT indicator_id,
       period_start::text, period_end::text, period_type::text,
       age_lower::text::smallint, age_upper::text::smallint,
       age_band_raw::text, gender::text, area_code::text, area_level::text,
       breakdown::jsonb, value::numeric, unit::text, value_type::text,
       data_time::text,
       'youth_youbike_station_ntpc' AS source_table
  FROM public.youth_youbike_station_ntpc
;
