-- ═══ dashboardmanager 的資料表定義 ═══
--
-- 為什麼需要這個檔案：
--   官方的 db-sample-data/dashboardmanager-demo.sql 只有 COPY 資料，
--   一個 CREATE TABLE 都沒有（實測 grep -c "CREATE TABLE" = 0）。
--   直接灌會全部失敗：ERROR: relation "public.component_charts" does not exist。
--   這裡依 Taipei-City-Dashboard-BE 的 GORM struct 補上 DDL。
--
-- 來源對照：
--   components / query_charts / component_charts / component_maps
--                          → app/models/componentConfig.go
--   dashboards / dashboard_groups → app/models/dashboard.go
--   groups                        → app/models/auth.go
--   contributors                  → app/models/contributor.go
--   issues                        → app/models/issue.go
--
-- 使用順序：先跑這支，再跑官方的 dashboardmanager-demo.sql。

-- ── 組件本體 ──
CREATE TABLE IF NOT EXISTS public.components (
    id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index varchar NOT NULL UNIQUE,
    name  varchar NOT NULL
);

-- ── 各城市的組件設定（含取數 SQL）──
-- 注意：Go struct 把 index 標成 unique，但多城市需要同 index 兩筆，
--       官方 sample data 本身就有 5 個 index 各出現兩次。
--       因此主鍵是 (index, city)，不是 index。
CREATE TABLE IF NOT EXISTS public.query_charts (
    index            varchar NOT NULL,
    history_config   json,
    map_config_ids   integer[],
    map_filter       json,
    time_from        varchar,
    time_to          varchar,
    update_freq      integer,
    update_freq_unit varchar,
    source           varchar,
    short_desc       text,
    long_desc        text,
    use_case         text,
    links            text[],
    contributors     text[],
    created_at       timestamp with time zone NOT NULL DEFAULT now(),
    updated_at       timestamp with time zone NOT NULL DEFAULT now(),
    query_type       varchar,
    query_chart      text,
    query_history    text,
    city             text NOT NULL,
    PRIMARY KEY (index, city)
);

-- ── 圖表樣式（跨城市共用，主鍵只有 index）──
CREATE TABLE IF NOT EXISTS public.component_charts (
    index varchar PRIMARY KEY,
    color varchar[],
    types varchar[],
    unit  varchar
);

-- ── 地圖圖層 ──
CREATE TABLE IF NOT EXISTS public.component_maps (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index    varchar NOT NULL,
    title    varchar NOT NULL,
    type     varchar NOT NULL,
    source   varchar NOT NULL,
    size     varchar,
    icon     varchar,
    paint    json,
    property json
);

-- ── 儀表板 ──
CREATE TABLE IF NOT EXISTS public.dashboards (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index      varchar NOT NULL UNIQUE,
    name       varchar NOT NULL,
    components integer[],
    icon       varchar,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- ── 權限群組（is_personal=false 才是公開儀表板）──
CREATE TABLE IF NOT EXISTS public.groups (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar,
    is_personal boolean DEFAULT false,
    create_by   integer
);

CREATE TABLE IF NOT EXISTS public.dashboard_groups (
    dashboard_id integer NOT NULL,
    group_id     integer NOT NULL,
    PRIMARY KEY (dashboard_id, group_id)
);

-- ── 貢獻者 ──
CREATE TABLE IF NOT EXISTS public.contributors (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     varchar NOT NULL,
    user_name   varchar NOT NULL,
    image       text,
    link        text NOT NULL,
    identity    varchar,
    description text,
    include     boolean NOT NULL DEFAULT false,
    created_at  timestamp with time zone NOT NULL DEFAULT now(),
    updated_at  timestamp with time zone NOT NULL DEFAULT now()
);

-- ── 問題回報 ──
CREATE TABLE IF NOT EXISTS public.issues (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         varchar NOT NULL,
    user_name     varchar NOT NULL,
    user_id       varchar NOT NULL,
    context       text,
    description   text NOT NULL,
    decision_desc text,
    status        varchar NOT NULL,
    updated_by    varchar NOT NULL,
    created_at    timestamp with time zone NOT NULL DEFAULT now(),
    updated_at    timestamp with time zone NOT NULL DEFAULT now()
);
